### ISSUE TITLE
Does not compile with vtk-6.0

### ISSUE THREAD

**Issue by uwesterh** [Xamla/torch-pcl#5]
When trying to build troch-plc with vtk-6.0, the compile process ends with an error:

```
[ 40%] Building CXX object CMakeFiles/pcl.dir/src/xyz.cpp.o
In file included from torch-pcl/src/xyz.cpp:7:0:
torch-pcl/src/mesh_sampling.cpp: In function ‘void sampleMesh(vtkPolyData*, pcl::PointCloud<pcl::PointXYZ>::Ptr, int, float)’:
torch-pcl/src/mesh_sampling.cpp:107:19: error: ‘class vtkTriangleFilter’ has no member named ‘SetInput’
   triangleFilter->SetInput(polydata);
                   ^
make[2]: *** [CMakeFiles/pcl.dir/src/xyz.cpp.o] Fehler 1
```

**Comment by andreaskoepf** [comment]
Was indeed changed with vtk-6, see [Replacement_of_SetInput](http://www.vtk.org/Wiki/VTK/VTK_6_Migration/Replacement_of_SetInput).

**Comment by andreaskoepf** [comment]
https://github.com/Xamla/torch-pcl/commit/4c7e4979b360355383a96ef5a6225ca063089782 should have fixed the compile error.
